#!/usr/bin/env fish

true
and conda activate base

and rm -rf (conda info --base)/envs/ml_service/
and conda env remove --name ml_service

and conda create --yes --name ml_service python
and conda activate ml_service
and pip install --upgrade --requirement requirements.txt
