#!/usr/bin/env bash

# Stop if one of the below line commands results in an error.
set -e

sudo apt update
sudo apt install -y libgl1-mesa-glx

# Install Anaconda3
wget -O Anaconda3.sh https://repo.anaconda.com/archive/Anaconda3-2023.03-1-Linux-x86_64.sh
chmod +x Anaconda3.sh
rm -rf ~/anaconda3
bash Anaconda3.sh -b
echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bashrc
. ~/.bashrc
. ~/anaconda3/etc/profile.d/conda.sh

# Delete a priorly setup Anaconda3 environment
conda activate base
rm -rf $(conda info --base)/envs/object_detection/
conda env remove --name object_detection

# Create a fresh Anaconda3 environment
conda create --yes --name object_detection python
conda activate object_detection
pip install --upgrade --requirement requirements.txt

# Copy the SSL certificate + key from the home directory,
# (to which we copied them using scp
# after creating them with mkcert)
cp ../{certificate,key}.pem .
