#!/usr/bin/env bash

# Stop if one of the below line commands
# results in an error.
set -e

# Without this line, we might get an error like:
# CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
. ~/anaconda3/etc/profile.d/conda.sh

conda activate base

rm -rf $(conda info --base)/envs/object_detection/
conda env remove --name object_detection

conda create --yes --name object_detection python
conda activate object_detection
pip install --upgrade --requirement requirements.txt
