#!/usr/bin/env bash

# Stop if one of the below line commands results in an error.
set -e

wget -O Anaconda3.sh https://repo.anaconda.com/archive/Anaconda3-2023.03-1-Linux-x86_64.sh
chmod +x Anaconda3.sh
rm -rf ~/anaconda3
bash Anaconda3.sh -b
echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bashrc
. ~/.bashrc

git clone https://github.com/Habimm/object_detection.git
cd object_detection/
. INSTALL

pkill -f "python api.py"
nohup python api.py > output.log 2>&1 &
ps aux | grep "python api.py"
