#!/usr/bin/env bash

# Stop if one of the below line commands results in an error.
set -e

# Run the web service,
# in such a way that it continues running,
# even after the SSH connection terminates.
pkill -f "python object_detection/api.py"
. ~/anaconda3/etc/profile.d/conda.sh
conda activate object_detection
nohup python object_detection/api.py > object_detection/output.log 2>&1 &
ps aux | grep "python object_detection/api.py"
cat object_detection/output.log
